--- 
HOST_URL: "my-account-test.atlassian.net"
USER_EMAIL: "javierlopez.jlp1@gmail.com"
#API_TOKEN: "ATATT3xFfGF0C52hE8SiXTIsYlvpxXE8AjUSoopD1qH77e-7PxPY3TvVr2GP1n9HBYDqVLAE4zoM0W5_sxrwFJ2NZGWyrBHRKSApXTYClgTIZav74O1F4a7bD4lnBsobuNMrPWjGLV0SG-AaJYWrrZ9IRe_xIHz-W0ezq4IwTcEGwfWDICdv8Uw=9201CA06"
API_TOKEN: "ATATT3xFfGF04Y2ub-I_vGRduTSgh2uTjCxZzTVlirEyUW_nu9sYCl01DY-eqb9SP7NxYPDbkUqnlnq15tipT0DjEm7_xeQ5we9BDGND0XQs-6eQi3McFkh1unF1ewqIw_BMr7PHPtw1BL8eGojsOHAtlwucDHmpy87AYexLnDfVYnlD5YRQ6M4=2F6CF462"
INCLUDE_ATTACHMENTS: "true"
DOWNLOAD_LOCALLY: "true"
